FORMAT: 1A
HOST: http://api.paneon.de/

# iRO API

iRO API is a simple API allowing clients to view the data of their iRO Databases.

# Group Public Data

## Public Project Collection [/data/{serial}/jobs/{sort}/{type}?{forceRefresh}]

### List all public projects [GET]

+ Parameters
    + serial: `12345-12345-12345` (text) - Serial of the target database
    + sort (enum[string], optional) - Sorting direction
        + Default: `desc`
        + Members
            + `asc`
            + `desc`
    + type (optional, enum[string])
        + Default: `normal`
        + Members
            + `normal`
            + `archiv`
    + forceRefresh (optional, boolean)
        + Default: false


+ Response 200 (application/json)

        {
            "cacheActive": false
            "cacheId": "1-joblist-normal-desc",
            "results": [
                {
                    "fm_id": "123",
                    "visible": 1,
                    "timestamp": 1463479812,
                    "last_modified": "05/12/2016 14:09:18",
                    "start_date": "2016-05-09",
                    "position": "Bereichsleiter X (m/w)",
                    "industry": "Elektrotechnik",
                    "location": "Westfalen",
                    "contact": "Max Müller",
                    "mail": "max.mueller@mueller.de",
                    "lang": "de",
                    "full_text": "Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Etiam porta sem malesuada magna mollis euismod. Curabitur blandit tempus porttitor. Donec ullamcorper nulla non metus auctor fringilla.\nDuis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Nullam quis risus eget urna mollis ornare vel eu leo. Aenean lacinia bibendum nulla sed consectetur. Vestibulum id ligula porta felis euismod semper. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Nullam id dolor id nibh ultricies vehicula ut id elit.",
                    "rewrite_link": "123-Bereichsleiter_X_m_w_Westfalen"
                },
                {
                    "fm_id": "456",
                    "visible": 1,
                    "timestamp": 1463479812,
                    "last_modified": "05/12/2016 14:09:18",
                    "start_date": "2016-05-09",
                    "position": "Trainee (m/w)",
                    "industry": "Elektrotechnik",
                    "location": "München",
                    "contact": "Max Müller",
                    "mail": "max.mueller@mueller.de",
                    "lang": "de",
                    "full_text": "Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Etiam porta sem malesuada magna mollis euismod. Curabitur blandit tempus porttitor. Donec ullamcorper nulla non metus auctor fringilla.\nDuis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Nullam quis risus eget urna mollis ornare vel eu leo. Aenean lacinia bibendum nulla sed consectetur. Vestibulum id ligula porta felis euismod semper. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Nullam id dolor id nibh ultricies vehicula ut id elit.",
                    "rewrite_link": "123-Trainee_m_w_Muenchen"
                }
            ]
        }

## Single public project [/data/{serial}/job-detail/{id}]

### Get detailed data of single public project [GET]

+ Parameters
    + serial: `12345-12345-12345` (text) - Serial of the target database
    + id: `1000` (number) - Project id

+ Response 200 (application/json)
    + Attributes (Project Response)

# Data Structures

## Project (object)
+ fm_id: 1 (number) - Represents the project id in iRO
+ visible: 1 (number)
+ timestamp: 1486567471 (number)
+ importCalendarDay: 2017163 (number)
+ last_modified_date: `08.02.2017 16:24:31` (string)
+ last_modified: 1486567471 (number)
+ start_date: `2017-02-08` (string) - Field "Start"
+ formatter: 1 (enum[number]) - 1 for Standard format or 2 for Markdown format
    + 1 - Standard
    + 2 - Markdown
+ rewrite_link: `372-Salesmanager`
+ Web_Detailslink: `http://www.your-website.com/job/372` (string) - Link to your website, please contact us how you can specify this
+ seo_title: `Salesmanager, `
+ seo_desc (string)
+ position: `Salesmanager` (string) - Field "Projekt"
+ industry: `Halbleiter` (string) - Field "Branche"
+ location: `Berlin` (string) - Field "Ort"
+ job_intro (string) - Field "Anonyme Einleitung für Webseite" bzw "Web-Intro"
+ job_description - Field "Die Position"
+ job_candidate - Field "Der ideale Kandidat"
+ job_desirability - Field "Attraktivität der Aufgabe"
+ job_resume - Field "Schlusstext"
+ contact: `Max Müller` (string) - Field "Web Berater"
+ contact_mail: `max.mueller@gmail.com` (string) - Field "Web E-Mail"
+ lang: `de` (enum[string]) - Field "Sprache"
    + "de" - Deutsch
    + "en" - Englisch
+ full_text (string) - Computed value for text search functionality, contains all text fields

## Project Response
+ results (Project, required)